version: '3.7'
services:

  account:
    build:
      context: './account'
    ports:
      - "4000:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env

  device:
    build:
      context: './device'
    ports:
      - "4001:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env

  drone:
    build:
      context: './drone'
    ports:
      - "4002:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env

  ledwall:
    build:
      context: './ledwall'
    ports:
      - "4003:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env

  restservice:
    build:
      context: './MainService'
    ports:
      - "4004:3000"
      - "8856:8856"
    depends_on:
      - database
    env_file:
      - ../secrets.env

  search:
    build:
      context: './search'
    ports:
      - "4005:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      #- /etc/letsencrypt/live/api.arnold-tim.de/: /etc/key/

    depends_on:
      - account
      - device
      - drone
      - ledwall
      - restservice
      - search

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ../secrets.env
    volumes:
      - databaseVolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database


volumes:
  databaseVolume: {}

