version: '3.7'
services:

  account:
    image: ghcr.io/ft-cloud/account:master
    ports:
      - "4000:3000"
    depends_on:
      - mongo
    env_file:
      - ../secrets.env
    restart: always

  device:

    image: ghcr.io/ft-cloud/device:master
    ports:
      - "4001:3000"
    depends_on:
      - mongo
    env_file:
      - ../secrets.env
    restart: always

  drone:

    image: ghcr.io/ft-cloud/drone:master
    ports:
      - "4002:3000"
    depends_on:
      - mongo
    env_file:
      - ../secrets.env
    restart: always



  #ledwall:

   # image: ghcr.io/ft-cloud/ledwall:master
   # ports:
   #   - "4003:3000"
   # depends_on:
   #   - database
   # env_file:
   #   - ../secrets.env
   # restart: always

  restservice:

    image: ghcr.io/ft-cloud/mainservice:master
    ports:
      - "4004:3000"
      - "8856:8856"
    depends_on:
      - mongo
    env_file:
      - ../secrets.env
    restart: always

#  search:
#    image: ghcr.io/ft-cloud/search:master
#    ports:
#      - "4005:3000"
#    depends_on:
#      - database
#    env_file:
#      - ../secrets.env
 #   restart: always

  usercontent:

    image: ghcr.io/ft-cloud/usercontent:master
    ports:
      - "4006:3000"
    depends_on:
      - mongo
    env_file:
      - ../secrets.env
    restart: always
    volumes:
      - usercontentdata:/usercontentdata

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      #- /etc/letsencrypt/live/api.arnold-tim.de/: /etc/key/

    depends_on:
      - account
      - device
      - drone
      - restservice

  #database:
   # image: mariadb:latest
   # ports:
   #   - "3306:3306"
   # restart: always
   # env_file:
   #   - ../secrets.env
   # volumes:
   #   - databaseVolume:/var/lib/mysql
  #phpmyadmin:
  #  image: phpmyadmin:latest
  #  restart: always
  #  ports:
  #    - "8080:80"
  #  environment:
  #    - PMA_ARBITRARY=1
  #  depends_on:
  #    - database
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
    env_file:
      - ../secrets.env
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--bind_ip_all" ]

  #rtmp:
  #  build: "./rtmp"
  #  ports:
  #    - "1935:1935"
  #    - "4007:4006"
  #  container_name: rtmp_server
  #  depends_on:
  #    - account



volumes:
  databaseVolume: {}
  mongodbdata: {}
  usercontentdata: {}

