version: '3.7'
services:

  account:
    build:
      context: './account'
    image: ftcloudaccount
    ports:
      - "4000:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env
    restart: always

  device:
    build:
      context: './device'
    image: ftclouddevice
    ports:
      - "4001:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env
    restart: always

  drone:
    build:
      context: './drone'
    image: ftclouddrone
    ports:
      - "4002:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env
    restart: always

  ledwall:
    build:
      context: './ledwall'
    image: ftcloudledwall
    ports:
      - "4003:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env
    restart: always

  restservice:
    build:
      context: './MainService'
    image: ftcloudmainservice
    ports:
      - "4004:3000"
      - "8856:8856"
    depends_on:
      - database
    env_file:
      - ../secrets.env
    restart: always

  search:
    build:
      context: './search'
    image: ftcloudsearch
    ports:
      - "4005:3000"
    depends_on:
      - database
    env_file:
      - ../secrets.env
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      #- /etc/letsencrypt/live/api.arnold-tim.de/: /etc/key/

    depends_on:
      - account
      - device
      - drone
      - ledwall
      - restservice
      - search

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ../secrets.env
    volumes:
      - databaseVolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
    env_file:
      - ../secrets.env
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  adminmongo:
    image: mrvautin/adminmongo:latest
    environment:
      PORT: 4321
      HOST: 0.0.0.0
      PASSWORD: Test
    ports:
      - "8081:4321"


volumes:
  databaseVolume: {}
  mongodbdata: {}

