version: '3.7'
services:
  account:
    build: './account'
    ports:
      - "4000:3000"
    depends_on:
      - database
  device:
    build: './device'
    ports:
      - "4001:3000"
    depends_on:
      - database
  drone:
    build: './drone'
    ports:
      - "4002:3000"
    depends_on:
      - database
  ledwall:
    build: './ledwall'
    ports:
      - "4003:3000"
    depends_on:
      - database
  restservice:
    build: './MainService'
    ports:
      - "4004:3000"
      - "8856:8856"
    depends_on:
      - database
  search:
    build: './search'
    ports:
      - "4005:3000"
    depends_on:
      - database
  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #- /etc/letsencrypt/live/api.arnold-tim.de/: /etc/key/
    depends_on:
      - account
      - device
      - drone
      - ledwall
      - restservice
      - search
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ../secrets.env
    volumes:
      - databaseVolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - database


volumes:
  databaseVolume: {}

