version: '3.7'
services:
  account:
    build: './account'
    ports:
      - "3000:3000"
    depends_on:
      - database
  device:
    build: './device'
    ports:
      - "3001:3000"
    depends_on:
      - database
  drone:
    build: './drone'
    ports:
      - "3002:3000"
    depends_on:
      - database
  ledwall:
    build: './ledwall'
    ports:
      - "3003:3000"
    depends_on:
      - database
  restservice:
    build: './MainService'
    ports:
      - "3004:3000"
    depends_on:
      - database
  search:
    build: './search'
    ports:
      - "3005:3000"
    depends_on:
      - database
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #- /etc/letsencrypt/live/api.arnold-tim.de/: /etc/key/
    depends_on:
      - account
      - device
      - drone
      - ledwall
      - restservice
      - search
  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ../secrets.env
    volumes:
      - databaseVolume:/var/lib/mysql


volumes:
  databaseVolume: {}

